# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8088
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      min-spare: 30
      max: 800

  shutdown: graceful

# 日志配置
logging:
  level:
    com.cheney.common.dao: trace
    org.springframework: warn
    com.cheney.manage.security: debug


  #配置数据源
spring:
  datasource:
    url: jdbc:mysql://47.114.133.218:3306/mine-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: uGIsJaiESUjpdzmt
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
    continue-on-error: true
#    schema:
#      - "classpath:db/schema.sql"
#    data:
#      - "classpath:db/data.sql"
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: MineHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 47.96.101.173
    port: 7639
    password: v9ms6Qhg5MvMiolF
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

custom:
  config:
    ignores:
      # 需要过滤的 post 请求
      post:
        - "/api/auth/login"
        - "/api/auth/logout"
      # 需要过滤的请求，不限方法
      pattern:
        - "/hello"

# token配置
jwt:
  config:
    # 令牌自定义标识
    header: Authorization
    # 令牌秘钥
    key: mineaaa
    # 令牌有效期（默认30秒）
    ttl: 1800
    remember: 604800

# MyBatis配置
mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.cheney.common.common.po

mine:
  # 是否在控制台打印 sql语句
  showsql: true